variables:
  CI_REGISTRY_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
  HELM_REPO_URL: "https://oauth2:$HELM_REPO_PAT@devops-gitlab.inno.ws/hanna.jyha/webapp-helm.git"
  IMAGE_REPOSITORY: $CI_REGISTRY_IMAGE
  
stages:
  - build_image
  - update_helm

build_job:
  stage: build_image
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "Сборка образа: $IMAGE_REPOSITORY:$CI_COMMIT_TAG"
    - docker build -t "$IMAGE_REPOSITORY:$CI_COMMIT_TAG" .
    - docker push "$IMAGE_REPOSITORY:$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG =~ /^dev-v.*$/
      when: on_success

update_helm_repo_job:
  stage: update_helm
  image: alpine/git:2.41.0
  before_script:
    - apk add --no-cache curl
    - curl -L https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -o /usr/local/bin/yq
    - chmod +x /usr/local/bin/yq
    
    - git config user.email "gitlab-ci-user@devops-gitlab.inno.ws"
    - git config user.name "GitLab CI Pipeline"
  script:
    - echo "Клонирование Helm-репозитория..."
    - git clone $HELM_REPO_URL helm-repo

    - cd helm-repo
    - echo "Текущий тег: $CI_COMMIT_TAG"

    - yq eval -i ".image.repository = \"$IMAGE_REPOSITORY\" | .image.tag = \"$CI_COMMIT_TAG\"" webapp-chart/values.yaml

    - git add webapp-chart/values.yaml
    - git commit -m "CI: Update image tag to $CI_COMMIT_TAG for $IMAGE_REPOSITORY" || echo "No changes to commit"
    - git push
    - echo "Helm-репозиторий обновлен."
  rules:
    - if: $CI_COMMIT_TAG =~ /^dev-v.*$/
      when: on_success
